### PR TITLE
Bump to 0.12.0.

### PR DESCRIPTION
**Pull request by bluescarni**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
hey @bluescarni I think something went wrong with the spdlog thing. any ideas?

**Comment by bluescarni** [comment]
@wolfv I think this is related to the dependency chain: heyoka.py depends on spdlog both explicitly and indirectly via the heyoka C++ library, plus the heyoka.py and heyoka versions also need to be synched together (due to the rapidly evolving API).

Bottom line, I thought that merging the PR and hoping for the bot to re-run the spdlog migration would be enough?

**Comment by wolfv** [comment]
hmmm, yeah currently the bot also has this dependency solver error: 

https://conda-forge.org/status/#other_migrations

Let's see if that resolves itself.

**Pull request merged**
