### PR TITLE
Bump v3 build

### PR DESCRIPTION
**Pull request by bluescarni**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bluescarni** [comment]
@h-vetinari is this looking ok?

**Comment by h-vetinari** [comment]
> @h-vetinari is this looking ok?

So you need to fix the `test: ...` thing in `conda-forge.yml`, but otherwise yes! Given that it doesn't contain the boost migrator, we'll have to let the bot do it, and for that, you'll have to add `v3.x` to `conda-forge.yml` under `bot_migration_branches:` on `main`, as I explained in https://github.com/conda-forge/cascade-feedstock/pull/19

**Comment by bluescarni** [comment]
@h-vetinari I fixed the test bit. I still don't fully understand the point about the ``migration_branches`` bit on ``main``, specifically:

- what is the precise syntax? In https://github.com/conda-forge/cascade-feedstock/pull/19 you mention a top-level ``abi_migration_branches`` but if I look at the docs [here](https://conda-forge.org/docs/maintainer/conda_forge_yml/#bot) it seems like it needs to go into a ``bot`` section. And in the comment on this very PR you are mentioning a ``bot_migration_branches`` section instead. Are all these options equivalent?
- should I just commit the ``abi_migration_branches`` changes directly on the ``main`` branch? Should I let it run the CI or should I prevent it via ``skpi ci`` or something like that?

**Comment by h-vetinari** [comment]
> Are all these options equivalent?

No, please follow the documentation. I was writing from memory, which is seldom a good idea. 😅 
To be sure, here's a concrete [example](https://github.com/conda-forge/arrow-cpp-feedstock/blob/main/conda-forge.yml) from the arrow feedstock.

**Comment by bluescarni** [comment]
@h-vetinari apologies for the delay, I have been swamped in the last few days.

I committed the changes to ``main``. Is this good to be merged now?

**Comment by h-vetinari** [comment]
No worries. :)



> I committed the changes to `main`. Is this good to be merged now?

Sure, let's go for it!

**Pull request merged**
